# Generated by Django 5.0.6 on 2026-09-03 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📰', max_length=50)),
                ('post_type', models.CharField(choices=[('gossip', 'Chisme Jugoso'), ('pana_debt', 'Cuentas entre Panas'), ('serious_debt', 'Deuda Serena')], default='gossip', max_length=20)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['post_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GossipTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#ff00e4', max_length=7)),
            ],
            options={
                'verbose_name': 'Etiqueta de Chisme',
                'verbose_name_plural': 'Etiquetas de Chismes',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Ej: 'Carlos me debe 1 Malta'", max_length=200, verbose_name='Título')),
                ('content', models.TextField(help_text='Describe el chisme, la deuda o el acuerdo entre panas.', verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='¿Pagada?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('post_type', models.CharField(choices=[('gossip', 'Chisme Jugoso'), ('pana_debt', 'Cuentas entre Panas'), ('serious_debt', 'Deuda Serena')], default='gossip', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('gossip_level', models.IntegerField(choices=[(1, '🌶️ Suavecito'), (2, '🌶️🌶️ Picante'), (3, '🌶️🌶️🌶️ Extra Picante')], default=1)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agreed_payment_date', models.DateField(blank=True, null=True)),
                ('debt_status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('disputed', 'En Disputa'), ('overdue', 'Vencido')], default='pending', max_length=20, null=True)),
                ('exact_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('guarantee_document', models.FileField(blank=True, null=True, upload_to='guarantees/')),
                ('legal_status', models.CharField(blank=True, choices=[('active', 'Activa'), ('in_collection', 'En Cobranza'), ('resolved', 'Resuelta')], default='active', max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspaper.category', verbose_name='Categoría')),
                ('gossip_tags', models.ManyToManyField(blank=True, to='newspaper.gossiptag')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('premium_views', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='newspaper.article')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('subscription', 'Suscripción'), ('credit_purchase', 'Compra de créditos'), ('content_purchase', 'Compra de contenido'), ('commission', 'Comisión'), ('refund', 'Reembolso')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspaper.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('creator', 'Content Creator')], default='free', max_length=20)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['post_type', '-created_at'], name='newspaper_a_post_ty_cf9a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'post_type'], name='newspaper_a_author__e67ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['debtor', 'debt_status'], name='newspaper_a_debtor__870ec3_idx'),
        ),
    ]
