# Generated by Django 5.0.6 on 2026-05-20 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Ej: 'Carlos me debe 1 Malta'", max_length=200, verbose_name='A quién y qué se debe')),
                ('content', models.TextField(help_text="Ej: 'Dijo que me la pagaba al salir de clases de Algoritmos y se fue corriendo'", verbose_name='El chisme/contexto')),
                ('image', models.ImageField(blank=True, help_text='La foto del culpable comiéndose la malta, o un meme gracioso de cobradera', null=True, upload_to='articles/', verbose_name='La evidencia física')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del préstamo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='El Acreedor')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['-created_at'],
            },
        ),
    ]
