# Generated by Django 5.0.6 on 2026-05-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Indica si esta deuda ya fue cobrada o perdonada por el acreedor.', verbose_name='¿Pagada?'),
        ),
    ]
